version: "3.3"
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Taipei
    volumes:
      - "/cms_docker_postgresql_data:/var/lib/postgresql/data"

  cms:
    container_name: cms
    build: .
    depends_on:
      - "db"
    environment:
      CMS_CONFIG: /usr/local/etc/cms-testdb.conf
      TZ: Asia/Taipei
    volumes:
      - "./codecov:/home/cmsuser/cms/codecov"
      - "./CreateByAaW:/home/cmsuser/cms/CreateByAaW"
      - /srv/cms:/var/local/lib/cms/ranking
    ports:
      - 8888:8888
      - 8889:8889
      - 8890:8890
    privileged: true
    
    command: >
      wait-for-it db:5432 -- bash -c '
      createdb --host=db --username=postgres cmsdb ;
      createdb --host=db --username=postgres cmsdbfortesting ;
      cmsInitDB ;
      sudo chown cmsuser:cmsuser ./codecov ;

      sudo sed -i "s/8e045a51e4b102ea803c06f92841a1fb/`python3 -c "from cmscommon import crypto; print(crypto.get_hex_random_key())"`/g" /usr/local/etc/cms.conf;
    
      cmsImportUser --all -L italy_yaml Sample_Contest;
      cmsImportContest -i -L italy_yaml Sample_Contest;
      cmsRankingWebServer &
      cmsResourceService -a 3;
      '
